### ISSUE TITLE
Extension view in browser failed

### ISSUE THREAD

**Issue by Tyriar** [hellopao/view-in-browser#1]
_From @Devdatta03 on March 28, 2016 5:44_
- VSCode Version:0.10.11
- OS Version:Windows 7

Steps to Reproduce:
1. Running the contributed command:'extension.viewInBrowser' failed
2. 

_Copied from original issue: Microsoft/vscode#4706_

**Comment by mamamusings** [comment]
I'm also getting this error, with VSCode 1.8.1 and Win 10 Enterprise (fully up to date). Focus is set to the html file. Error occurs using default browser, and/or setting a custom browser.

**Comment by wendyperalta** [comment]
I'm getting this issue when I do 'Cmd + Shift + P' and type "View in Browser" then click Enter. If I right-click the html file and select "View in Browser" I do not get an error. Also don't get an error when I do Cmd + F1. I'm using Visual Studio Code v 1.8.1 , View In Browser v 0.0.5.

**Comment by jaimearroyo** [comment]
Gotcha, in my case I had the .html file extension associated to a notepad app, I associated it again to a browser and voila. (hope it helps someone).

**Comment by vindicatorr** [comment]
I'm encountering this as well (first time trying it): "Running the contributed command:'extension.viewInBrowser' failed."

Archlinux
Google Chrome: 56.0.2924.87
VS Code:
```
Version 1.11.0-insider
Commit 84e56fc527047223a6ad22c31a906d4a579680d0
Date 2017-03-03T07:08:55.738Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
User Settings: "view-in-browser.customBrowser": "chrome"

**Comment by mrdulin** [comment]
same issue.
System: OSX 
View in browser 0.0.5

**Comment by elboletaire** [comment]
Same here using Ubuntu 16.04 and code 1.12.2. I've just discovered this plugin but... it seems I need to find another one 😞 

BTW, why was this issue closed? 😕

**Comment by saha6984** [comment]
I also have same issue having things updated but getting below issue while running
Running the contributed command:'extension.viewInBrowser' failed.

If this issue closed then can anyone please tell me where can i find solution

**Comment by AChaoZJU** [comment]
same issue
System: macOS 10.12.5
vscode: 1.12.2 (1.12.2)

**Comment by tminina** [comment]
The only right-click on the file name works for me on Win10.

**Comment by Danilux** [comment]
I'm getting this too, I can't even Ctrl + F1, an on right-click view in browser won't show up.
Windows 10 Insiders, latest Vs code

**Comment by irsal-id** [comment]
I also have this issue on Ubuntu 17. 04 even when I change the user setting like this "view-in-browser.customBrowser": "chrome"

**Comment by juanrebolledo17** [comment]
Linux manjaro here. And same issue. i guess, i'll start looking other extension.

**Comment by technoiswatchingyou** [comment]
Same here.
VSCode 1.17.1
MacOS 10.13.1

**Comment by RogueToad** [comment]
Same issue here, manjaro linux. I'm now using this extension instead:
https://marketplace.visualstudio.com/items?itemName=techer.open-in-browser

**Comment by PersyJack** [comment]
I get this if I open command list (F1) and chose "View in Browser. However, Ctrl + F1 combination works fine.

**Comment by jake-lewis** [comment]
Still getting this issue. Just updated to latest version of code (1.24.0), it was fine before.

Interestingly it gives a warning when using the shortcut Ctrl + F1, but it gives an error when using the command pallette

**Comment by jdswee** [comment]
same with you @jsjlewis96 
windows 10; vscode 1.24.4; view in browser 0.05

**Comment by ryan-117** [comment]
same issue;
![image](https://user-images.githubusercontent.com/24773896/42263822-b3153be6-7fa1-11e8-85b5-c109b3cdb043.png)
The only right-click on the file name works for me on Win10. Ctrl+F1 doesn't work.

**Comment by AUROCHSY** [comment]
I have the same question,None of the start ways I can use

**Comment by zjtt** [comment]
I have the same question.
![_20180720114045](https://user-images.githubusercontent.com/22001904/42986467-3b233c94-8c28-11e8-9509-ac03bd9f6007.png)

**Comment by ChlorineLv** [comment]
Same issue, 
"Ctrl F1" and "Ctrl Shift P > View in browser" don't work,
only right click works, in the file list.
VS Code Version: 1.25.1
View In Browser (qinjia) Version: 0.0.5
OS: Window10 Family 10.0.17134
However,
when i install another one: view-in-browser (Kopp Ho) Version 1.0.5, 
and then, set the “keybindings.json", and "Ctrl F1" works again
![image](https://user-images.githubusercontent.com/22474522/43063133-a0e679da-8e8d-11e8-953b-3d0056873e61.png)
![image](https://user-images.githubusercontent.com/22474522/43063157-b2447132-8e8d-11e8-9788-33316086e4c1.png)

**Comment by mgeng** [comment]
I have same issue
Windows10
Version: 1.25.1
Architecture: x64

**Comment by anand853** [comment]
I'm getting the same error at Mac 10.13..6
VS Version 1.26.1 (1.26.1)
![screen shot 2018-08-22 at 4 38 32 pm](https://user-images.githubusercontent.com/3404193/44489576-d6a7ef00-a629-11e8-9e62-a56b7ecd90fa.png)

**Comment by suchanglin** [comment]
how to solve the problem

**Comment by rewaant** [comment]
I'm on Debian Stretch with Gnome 3, solved it by adding
`"open-in-browser.default":  "firefox"` to user settings.
Make sure "firefox" is added to your path or replace with your browser choice.

**Comment by ChlorineLv** [comment]
> Same issue,
> "Ctrl F1" and "Ctrl Shift P > View in browser" don't work,
> only right click works, in the file list.
> VS Code Version: 1.25.1
> View In Browser (qinjia) Version: 0.0.5
> OS: Window10 Family 10.0.17134
> However,
> when i install another one: view-in-browser (Kopp Ho) Version 1.0.5,
> and then, set the “keybindings.json", and "Ctrl F1" works again
> ![image](https://user-images.githubusercontent.com/22474522/43063133-a0e679da-8e8d-11e8-953b-3d0056873e61.png)
> ![image](https://user-images.githubusercontent.com/22474522/43063157-b2447132-8e8d-11e8-9788-33316086e4c1.png)

well, I had reseted my PC few days ago and need to install VSCode again.
VSCode version: 1.27.1
Chrome: 61.0.3163.100 (shown in vscode)
Chrome: 69.0.3497.92 (shown in Chrome About)
Windows 10: Family 1803, 17134.254

installed "view-in-browser" (by Koppt Ho) and "View In Browser" (by qinjia) together,
then reload,
it works.

Don't know why.

**Comment by kunal812eee** [comment]
@peachQAQ thats works . thanks bro.

**Comment by ghost** [comment]
install 2 extension it work for me.

![pic01](https://user-images.githubusercontent.com/43635690/46133553-feaef180-c26a-11e8-983c-af348b54dc7e.PNG)

![pic02](https://user-images.githubusercontent.com/43635690/46133554-feaef180-c26a-11e8-9565-a7a964e5ebdd.png)

**Comment by cybervigilante** [comment]
I've had it with Visual Studio Code. I spend more time trying to get things working than I do studying programming. It's a "work in progress" for sure ;)

**Comment by NemoDream** [comment]
I have same issue.
I`m install a plugin [Open in Browser](https://marketplace.visualstudio.com/items?itemName=techer.open-in-browser) and press "Alt+B".
![image](https://user-images.githubusercontent.com/21306508/61677906-cca7d800-ad33-11e9-9ce1-d523b958245a.png)

**Comment by FabioSF10** [comment]
I have a solution. With me I just choose directory (after reloading the CPU). And after this I click with right bottom on mouse in the archive /open in browser. It's works

Portuguese: Eu apenas escolhi um diretório, nas ferramentas ao lado esquerdo "No folder opened" e cliquei em open folder. Escolhi o  diretório, depois cliquei com o botão direito do mouse no arquivo a ser aberto /open in browser. Funcionou comigo
![issue](https://user-images.githubusercontent.com/67606159/91620175-8f197380-e965-11ea-81f2-aad9fb89d208.png)
