### ISSUE TITLE
不知道哪个2货，更新了一个文件，导致ctrl + F1 提示 “command 'extension.viewInBrowser' not found”

### ISSUE THREAD

**Issue by rufeng2015** [hellopao/view-in-browser#9]
I updated the latest view in browser, but when using Ctrl +F1, prompted an error, please repair as soon as possible, thank you

command 'extension.viewInBrowser' not found

**Comment by fra-apollo** [comment]
+1

**Comment by hellopao** [comment]
@rufeng2015 已经修复了，你再更新下。

前几天merge了一个pr，那个人用了个新的库，把依赖写到了devDependencies，打包到商店是不会装那个依赖的，我没仔细看。不好意思。
